version: '3.9'

services:
  gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    depends_on:
      - auth-service
      - ads-service
    restart: unless-stopped

  auth-service:
    build: ./auth-service
    ports:
      - "8001:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/auth/health"]
      interval: 5s
      timeout: 3s
      retries: 5

  ads-service:
    build: ./ads-service
    ports:
      - "8002:8000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DB=ads_db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/ads/health"]
      interval: 5s
      timeout: 3s
      retries: 5

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
